export const pricingInfo = [
  {
    type: "Free",
    price: 0,
    noOfUsers: "Single User",
    storage: "5GB",
    publicProjects: "Unlimited",
    accessType: "Community Access",
    privateProjects: "Unlimited",
    checkPrivateProjects: false,
    support: "Dedicated Phone Support",
    checkSupport: false,
    subdomain: "Free",
    checkSubdomain: false,
    reports: "Monthly Status Reports",
    checkReports: false,
  },
  {
    type: "Plus",
    price: 9,
    noOfUsers: "5 Users",
    storage: "50GB",
    publicProjects: "Unlimited",
    accessType: "Community Access",
    privateProjects: "Unlimited",
    checkPrivateProjects: true,
    support: "Dedicated Phone Support",
    checkSupport: true,
    subdomain: "Free",
    checkSubdomain: true,
    reports: "Monthly Status Reports",
    checkReports: false,
  },
  {
    type: "Pro",
    price: 49,
    noOfUsers: "Unlimited Users",
    storage: "150GB",
    publicProjects: "Unlimited",
    accessType: "Community Access",
    privateProjects: "Unlimited",
    checkPrivateProjects: true,
    support: "Dedicated Phone Support",
    checkSupport: true,
    subdomain: "Unlimited",
    checkSubdomain: true,
    reports: "Monthly Status Reports",
    checkReports: true,
  },
];
